[metadata]
name    = "transfer"


[global]
plan    = "testbed"
case    = "transfer"
builder = "exec:go"
runner  = "local:exec"

total_instances = 2

[[groups]]
id = "nodes"
instances = { count = 2 }

[groups.build]

[groups.run]
[groups.run.test_params]
input_data = "random"
file_size = "500000000,1000000000,1500000000,2000000000,2500000000,3000000000"
run_timeout_secs = "3000000"
timeout_secs = "12000000"
run_count = "1"
leech_count= "1"
passive_count = "0"
max_connection_rate = "100"
latency_ms= "0"
bandwidth_mb= "0"
enable_tcp= "false"
enable_dht= "false"
node_type = "rawLibp2p"