[metadata]
name    = "rfcBBL103A"
author  = "adlrocha"

[global]
plan    = "beyond-bitswap"
case    = "ipfs-transfer"
builder = "exec:go"
runner  = "local:exec"

total_instances = 18

[[groups]]
id = "nodes"
instances = { count = 18 }

    [groups.build]
    dependencies = [
        { module = "github.com/ipfs/go-bitswap", version = "bc3df6bd01b7f3d9be9d44e9a83b0663abf0230c"}
    ]

    [groups.run]
        [groups.run.test_params]
            run_count = "5"
            leech_count="15"
            max_connection_rate="100"
            file_size="15728640,31457280,47185920,57671680"

    # test_params = { run_count = 5, leech_count = 15, max_connection_rate=100, input_data="random", file_size=[15728640,31457280,47185920,57671680]}
